version: '3.2'
services:
  nginx: # webserver
    build:
      context: ./
      dockerfile: docker/conf/nginx.docker
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - php-fpm
      - db

  php-fpm:
    build:
      context: ./
      dockerfile: docker/conf/php-fpm.docker
    restart: always
    volumes:
      - ./:/var/www/html
#    environment:
#      - "DB_PORT=${DB_PORT}"
#      - "DB_HOST=${DB_HOST}"
#      - "DB_NAME=${DB_NAME}"
#      - "DB_USER=${DB_USER}"
#      - "DB_PASSWORD=${DB_PASSWORD}"


  db:
    image: postgres:14.1
    restart: always
    #    volumes:
    #      - ./storage/docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USErmR}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "54321:5432"

